//test data
var debug_data = [
	{ 
		module:"banner",   //test 商品详情
		title:"顶部banner",
		data:[
			{
				imgurl:"http://img04.taobaocdn.com/bao/uploaded/i4/TB1xW_yIpXXXXauXVXXXXXXXXXX_!!0-item_pic.jpg",
				clickurl:"http://s.click.taobao.com/DmaEPVx"
			}
		]
	},
	{
		module:"fourgrid",//四宫格模块
		title:"有好评"
		data:[
			{
				imgurl:"http://img03.taobaocdn.com/bao/uploaded/i3/TB1hTwcKVXXXXbRXpXXXXXXXXXX_!!0-item_pic.jpg",
				clickurl:"http://s.click.taobao.com/6CWEPVx"
			},
			{
				imgurl:"http://img03.taobaocdn.com/bao/uploaded/i3/TB1_n4hKVXXXXbxapXXXXXXXXXX_!!0-item_pic.jpg",	
				clickurl:"http://s.click.taobao.com/2VZEPVx"		
			},
			{
				imgurl:"http://img03.taobaocdn.com/bao/uploaded/i3/2130846165/TB2xxQdtFXXXXXjXpXXXXXXXXXX_!!2130846165.jpg",
				clickurl:"http://s.click.taobao.com/0ZcEPVx"
			},
			{
				imgurl:"http://img04.taobaocdn.com/bao/uploaded/i4/TB1E3_HKVXXXXaoaXXXXXXXXXXX_!!0-item_pic.jpg",
				clickurl:"http://s.click.taobao.com/oeUEPVx"
			}
		]
	},
	{
		module:"fourgrid2",//四宫格模块
		title:"剁好物",
		data:[
			{
				imgurl:"http://img04.taobaocdn.com/bao/uploaded/i4/TB1cQNxKVXXXXcUXVXXXXXXXXXX_!!0-item_pic.jpg",
				clickurl:"http://s.click.taobao.com/gcREPVx"
			},
			{
				imgurl:"http://img02.taobaocdn.com/bao/uploaded/i2/TB1zpPSHFXXXXbWaXXXXXXXXXXX_!!0-item_pic.jpg",
				clickurl:"http://s.click.taobao.com/zRXEPVx"
			},
			{
				imgurl:"http://img03.taobaocdn.com/bao/uploaded/i3/TB1Pk0XKVXXXXbtXVXXXXXXXXXX_!!0-item_pic.jpg",
				clickurl:"http://s.click.taobao.com/yyYEPVx"
			},
			{
				imgurl:"http://img04.taobaocdn.com/bao/uploaded/i4/TB16WWsLXXXXXXyXFXXXXXXXXXX_!!0-item_pic.jpg",
				clickurl:"http://s.click.taobao.com/7DYEPVx"
			}
		]
	},
	{
		title:"品质生活",
		module:"goodlife",//爆款模块
		data:[
			{
				title:"暖男保温壶",
				price:29.90,
				imgurl:"http://img02.taobaocdn.com/bao/uploaded/i2/TB1eXqlLXXXXXcvapXXXXXXXXXX_!!0-item_pic.jpg",
				clickurl:"http://s.click.taobao.com/n9TEPVx"
			},
			{
				title:"美式咖啡机",
				price:79.00,
				imgurl:"http://img03.taobaocdn.com/bao/uploaded/i3/TB1BP9_KpXXXXa3XpXXXXXXXXXX_!!0-item_pic.jpg",
				clickurl:"http://s.click.taobao.com/WAUEPVx"
			},
			{
				title:"海尔吸尘器",
				price:99.90,
				imgurl:"http://img01.taobaocdn.com/bao/uploaded/i1/TB1XmvhLXXXXXcgXpXXXXXXXXXX_!!0-item_pic.jpg",
				clickurl:"http://s.click.taobao.com/pyYEPVx"
			}
		]
	},
	{
		title:"3C小家电小数码",
		module:"electronProduct",
		data:[
			{
				title:"笔记本散热器",
				price:18.50,
				imgurl:"http://img02.taobaocdn.com/bao/uploaded/i2/TB1S74YMpXXXXahXVXXXXXXXXXX_!!0-item_pic.jpg",
				clickurl:"http://s.click.taobao.com/p0aEPVx"
			},	
			{
				title:"电动剃须刀",
				price:18.90,
				imgurl:"http://img03.taobaocdn.com/bao/uploaded/i3/TB198lwKFXXXXXoaXXXXXXXXXXX_!!0-item_pic.jpg",
				clickurl:"http://s.click.taobao.com/p9TEPVx"
			},
			{
				title:"电脑小音响",
				price:19.90,
				imgurl:"http://img02.taobaocdn.com/bao/uploaded/i2/TB1p9jFKVXXXXb7XpXXXXXXXXXX_!!0-item_pic.jpg",
				clickurl:"http://s.click.taobao.com/vPTEPVx"
			}
		]
	},
	{
		title:"车载专享价",
		module:"carProduct",
		data:[
			{
				title:"车载手机支架",
				price:5.80,
				imgurl:"http://img04.taobaocdn.com/bao/uploaded/i4/TB18jn7KVXXXXcmXVXXXXXXXXXX_!!0-item_pic.jpg",
				clickurl:"http://s.click.taobao.com/FvVEPVx"
			},
			{
				title:"吸尘器充气泵",
				price:68.00,
				imgurl:"http://img03.taobaocdn.com/bao/uploaded/i3/TB1CY7XKFXXXXbAXFXXXXXXXXXX_!!0-item_pic.jpg",
				clickurl:"http://s.click.taobao.com/wyYEPVx"
			},
			{
				title:"全包围汽车脚垫",
				price:69.00,
				imgurl:"http://img02.taobaocdn.com/bao/uploaded/i2/TB1Uj3vLVXXXXaUapXXXXXXXXXX_!!0-item_pic.jpg",
				clickurl:"http://s.click.taobao.com/b7SEPVx"
			}
		]
	},
	{
		title:"编辑精选",
		module:"recommend",
		data:[
			{
				title:"【电子血压计】智能家用上臂式.全自动.高精准",
				price:118.00,
				imgurl:"http://img01.taobaocdn.com/bao/uploaded/i1/TB1zgg4KFXXXXbIXFXXXXXXXXXX_!!0-item_pic.jpg",
				clickurl:"http://s.click.taobao.com/NGbEPVx"
			},
			{
				title:"【蔓越莓巧克力蛋卷】顽固老爹奶心脆皮卷138g",
				price:14.80,
				imgurl:"http://img04.taobaocdn.com/bao/uploaded/i4/475349436/TB2m7pKtFXXXXaEXpXXXXXXXXXX_!!475349436.jpg",
				clickurl:"http://s.click.taobao.com/yAVEPVx"
			},
			{
				title:"【入耳式耳塞】iPhone/安卓手机通用",
				price:15.00,
				imgurl:"http://img02.taobaocdn.com/bao/uploaded/i2/TB1uwecKpXXXXbhXXXXXXXXXXXX_!!0-item_pic.jpg",
				clickurl:"http://s.click.taobao.com/vTYEPVx"
			},
			{
				title:"【飞利浦充电宝】10000毫安超薄便携移动电源",
				price:169.00,
				imgurl:"http://img03.taobaocdn.com/bao/uploaded/i3/TB17geBKFXXXXXKXXXXXXXXXXXX_!!0-item_pic.jpg",
				clickurl:"http://s.click.taobao.com/5ZcEPVx"
			},
			{
				title:"【碳素羽毛球拍】ENPEX/乐士1支2支装正品包邮",
				price:19.90,
				imgurl:"http://img02.taobaocdn.com/bao/uploaded/i2/TB1f5epJVXXXXXgXpXXXXXXXXXX_!!0-item_pic.jpg",
				clickurl:"http://s.click.taobao.com/n0aEPVx"
			}
		]
	}
];

